name: Automatic update to flake.lock

on:
  schedule:
    - cron: "45 16 * * 5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31.6.0
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Update nix flake
        run: nix flake update

      - name: Make metadata
        id: meta
        run: |
          {
            echo "date=$(date +%Y-%m-%d)"
          } >> $GITHUB_OUTPUT

      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          title: "chore(flake): update nix flake at ${{ steps.meta.outputs.date }}"
          commit-message: "chore(flake): update nix flake at ${{ steps.meta.outputs.date }}"
          branch: "update-nix-flake-at-${{ steps.meta.outputs.date }}"
          add-paths: |
            flake.lock
